Importing Necessary Liberaries

In [1]:
import numpy as np
import pandas as pd

# Employee Salary Adjustment

A company stores salaries in a NumPy array.
salaries = np.array([45000, 52000, 61000, 48000, 75000])
Tasks:
1. Increase all salaries by 10%.
2. Find the average salary.
3. Find the maximum and minimum salary.
4. Print salaries greater than 60000.


In [2]:
salaries= np.array([45000,52000,61000,48000,75000])

In [3]:
# increasing all salaries by 10%

new_salaries= salaries*1.10
new_salaries

array([49500., 57200., 67100., 52800., 82500.])

In [4]:
# findingg average salary

avg_salary_old= np.average(salaries)
avg_salary_new= np.average(new_salaries)

print("Average Salary Before Increase: ", avg_salary_old)
print("Average Salary After Increase: ", avg_salary_new)


Average Salary Before Increase:  56200.0
Average Salary After Increase:  61820.0


In [5]:
# finding the Maximum and Minimum Salary

max_salary_old= np.max(salaries)
min_salary_old= np.min(salaries)

max_salary_new= np.max(new_salaries)
min_salary_new= np.min(new_salaries)

print("Maximum Salary Before Increase: ", max_salary_old)
print("Minimum Salary Before Increase: ", min_salary_old)
print("Maximum Salary After Increase: ", max_salary_new)
print("Minimum Salary After Increase: ", min_salary_new)

Maximum Salary Before Increase:  75000
Minimum Salary Before Increase:  45000
Maximum Salary After Increase:  82500.0
Minimum Salary After Increase:  49500.00000000001


In [6]:
# finding salaries greater than 60000

salaries_greater_than_60000= salaries[salaries>60000]
salaries_greater_than_60000

array([61000, 75000])

# Sales Data Analysis

Daily sales of a store for 10 days:
sales = np.array([120,150,180,200,170,160,210,220,190,175])
Tasks:
1. Compute total sales.
2. Compute mean and standard deviation.
3. Identify days where sales exceeded the average.
4. Normalize the sales using Min-Max scaling



In [7]:
sales = np.array([120,150,180,200,170,160,210,220,190,175])

In [8]:
total_sales=np.sum(sales)
print(' Total_sales is ',total_sales)


 Total_sales is  1775


In [9]:
# Mean and standard deviation

mean_sales= np.mean(sales)
std_sales= np.std(sales)

print(' Mean_sales is ',mean_sales)
print(' Std_sales is', std_sales)

 Mean_sales is  177.5
 Std_sales is 28.217902119044926


In [10]:
# To identify days where sales exceeded the average

days_above_average_sales= sales[sales>mean_sales]
days_above_average_sales

array([180, 200, 210, 220, 190])

In [11]:
# Normalize the sales using Min-Max scaling.

min_sales= np.min(sales)
max_sales= np.max(sales)

normalized_sales= (sales-min_sales)/(max_sales-min_sales)
normalized_sales

array([0.  , 0.3 , 0.6 , 0.8 , 0.5 , 0.4 , 0.9 , 1.  , 0.7 , 0.55])

# Matrix Operations for Business Data

A company has sales data for 3 products across 4 regions.
sales_matrix = np.array([
[120,140,130,150],
[80,90,100,95],
[200,210,190,205]
])
Tasks:
1. Find total sales per product.
2. Find total sales per region.
3. Identify the best performing product.
4. Identify the region with highest sales.

In [12]:
sales_matrix = np.array([
[120,140,130,150],
[80,90,100,95],
[200,210,190,205]
])


In [13]:
sales_matrix

array([[120, 140, 130, 150],
       [ 80,  90, 100,  95],
       [200, 210, 190, 205]])

In [14]:
# total sales per product

total_sales_per_product= np.sum(sales_matrix, axis=1)
total_sales_per_product

array([540, 365, 805])

In [15]:
# total sales per region.

total_sales_per_region= np.sum(sales_matrix, axis=0)
total_sales_per_region

array([400, 440, 420, 450])

In [16]:
# Identify the best performing product.

best_performing_product= np.argmax(total_sales_per_product)
print('The best perfoming product is Product number : ',best_performing_product)

The best perfoming product is Product number :  2


In [17]:
#  region with highest sales.

best_performing_region= np.argmax(total_sales_per_region)
print('The best perfoming region is  : ',best_performing_region + 1)

The best perfoming region is  :  4


# Employee Dataset Exploration

Create a DataFrame:
data = {
'Employee':['A','B','C','D','E','F'],
'Department':['HR','IT','IT','Finance','HR','Finance'],
'Salary':[50000,65000,70000,72000,52000,68000],
'Experience':[2,5,7,6,3,4]
}
Tasks:
1. Convert this dictionary into a DataFrame.
2. Display basic statistics of the dataset.
3. Find the average salary per department.
4. Identify employees with experience greater than 4 years.
5. Add a new column Bonus = 10% of salary

In [18]:
data = {
'Employee':['A','B','C','D','E','F'],
'Department':['HR','IT','IT','Finance','HR','Finance'],
'Salary':[50000,65000,70000,72000,52000,68000],
'Experience':[2,5,7,6,3,4]
}

In [19]:
data

{'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
 'Department': ['HR', 'IT', 'IT', 'Finance', 'HR', 'Finance'],
 'Salary': [50000, 65000, 70000, 72000, 52000, 68000],
 'Experience': [2, 5, 7, 6, 3, 4]}

In [20]:
# Converting into Dataframe

Employee_dataframe= pd.DataFrame(data)
Employee_dataframe

,Employee,Department,Salary,Experience
0,A,HR,50000,2
1,B,IT,65000,5
2,C,IT,70000,7
3,D,Finance,72000,6
4,E,HR,52000,3
5,F,Finance,68000,4


In [21]:
#  basic statistics of the dataset

Employee_dataframe.describe()

,Salary,Experience
count,6.000000,6.000000
mean,62833.333333,4.500000
std,9474.527253,1.870829
min,50000.000000,2.000000
25%,55250.000000,3.250000
50%,66500.000000,4.500000
75%,69500.000000,5.750000
max,72000.000000,7.000000


In [22]:
# average salary per department.

average_salary_per_department= Employee_dataframe.groupby('Department')['Salary'].mean()
average_salary_per_department

,Salary
Department,
Finance,70000.0
HR,51000.0
IT,67500.0


In [23]:
#  Employees with experience greater than 4 years.

experienced_employees= Employee_dataframe[Employee_dataframe['Experience']>4]
experienced_employees


,Employee,Department,Salary,Experience
1,B,IT,65000,5
2,C,IT,70000,7
3,D,Finance,72000,6


In [24]:
# new column Bonus = 10% of salary.

Employee_dataframe['Bonus']= Employee_dataframe['Salary']*0.1
Employee_dataframe

,Employee,Department,Salary,Experience,Bonus
0,A,HR,50000,2,5000.0
1,B,IT,65000,5,6500.0
2,C,IT,70000,7,7000.0
3,D,Finance,72000,6,7200.0
4,E,HR,52000,3,5200.0
5,F,Finance,68000,4,6800.0


# Missing Data Handling

Dataset:
data = {
'Name':['John','Anna','Peter','Linda','David'],
'Age':[28, np.nan, 35, 32, np.nan],
'Salary':[50000,54000,np.nan,58000,60000]
}
Tasks:
1. Detect missing values.
2. Replace missing Age with mean age.
3. Replace missing Salary with median salary.
4. Remove rows with any remaining missing values.

In [25]:
data = {
'Name':['John','Anna','Peter','Linda','David'],
'Age':[28, np.nan, 35, 32, np.nan],
'Salary':[50000,54000,np.nan,58000,60000]
}


In [26]:
Data_df= pd.DataFrame(data)
Data_df

,Name,Age,Salary
0,John,28.0,50000.0
1,Anna,NaN,54000.0
2,Peter,35.0,NaN
3,Linda,32.0,58000.0
4,David,NaN,60000.0


In [27]:
# Missing Values

missing_values= Data_df.isnull()
missing_values

,Name,Age,Salary
0,False,False,False
1,False,True,False
2,False,False,True
3,False,False,False
4,False,True,False


In [28]:
# Replacing Age with missing values

mean_age = Data_df['Age'].mean()
Data_df['Age'].fillna(mean_age, inplace=True)
Data_df

/tmp/ipykernel_34148/4203513842.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Data_df['Age'].fillna(mean_age, inplace=True)


,Name,Age,Salary
0,John,28.000000,50000.0
1,Anna,31.666667,54000.0
2,Peter,35.000000,NaN
3,Linda,32.000000,58000.0
4,David,31.666667,60000.0


In [29]:
# Replace missing Salary with median

median_salary= Data_df['Salary'].median()
Data_df['Salary'].fillna(median_salary, inplace=True)

Data_df

/tmp/ipykernel_34148/1296764732.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Data_df['Salary'].fillna(median_salary, inplace=True)


,Name,Age,Salary
0,John,28.000000,50000.0
1,Anna,31.666667,54000.0
2,Peter,35.000000,56000.0
3,Linda,32.000000,58000.0
4,David,31.666667,60000.0


In [30]:
# Remove rows with any remaining missing values

Data_df.dropna(inplace=True)
Data_df

,Name,Age,Salary
0,John,28.000000,50000.0
1,Anna,31.666667,54000.0
2,Peter,35.000000,56000.0
3,Linda,32.000000,58000.0
4,David,31.666667,60000.0


# Sales Performance Analysis

Dataset:
sales_data = {
'Region':['North','South','East','West','North','South','East','West'],
'Salesperson':['A','B','C','D','E','F','G','H'],
'Sales':[12000,15000,13000,17000,16000,14000,15500,16500]
}
Tasks:
1. Find total sales per region.
2. Identify the top salesperson.
3. Compute average sales across regions.
4. Sort the dataset by sales descending.


In [31]:
sales_data = {
'Region':['North','South','East','West','North','South','East','West'],
'Salesperson':['A','B','C','D','E','F','G','H'],
'Sales':[12000,15000,13000,17000,16000,14000,15500,16500]
}

In [32]:
sales_df = pd.DataFrame(sales_data)
sales_df
sales_df

,Region,Salesperson,Sales
0,North,A,12000
1,South,B,15000
2,East,C,13000
3,West,D,17000
4,North,E,16000
5,South,F,14000
6,East,G,15500
7,West,H,16500


In [33]:
# Total sales per region

region_sales = sales_df.groupby('Region')['Sales'].sum()
print(region_sales)

Region
East     28500
North    28000
South    29000
West     33500
Name: Sales, dtype: int64


In [34]:
# Top Sales person

top_salesperson = sales_df.loc[sales_df['Sales'].idxmax()]
print(top_salesperson)

Region          West
Salesperson        D
Sales          17000
Name: 3, dtype: object


In [35]:
# Average sales across regions

avg_region_sales = sales_df.groupby('Region')['Sales'].mean()
print(avg_region_sales)

Region
East     14250.0
North    14000.0
South    14500.0
West     16750.0
Name: Sales, dtype: float64


In [36]:
# Sort dataset by sales (descending)

sorted_df = sales_df.sort_values(by='Sales', ascending=False)
print(sorted_df)

  Region Salesperson  Sales
3   West           D  17000
7   West           H  16500
4  North           E  16000
6   East           G  15500
1  South           B  15000
5  South           F  14000
2   East           C  13000
0  North           A  12000


# Customer Purchase Analysis

Dataset:
data = {
'CustomerID':[101,102,103,104,105,106,107],
'Age':[25,45,35,50,23,40,60],
'PurchaseAmount':[250,600,400,800,150,700,900],
'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai','Delhi','Chennai']
}

asks:
1. Find the average purchase amount by city.
2. Identify customers with purchase above overall average.
3. Find the city generating the highest revenue.
4. Create a column Age_Group:
o <30 → Young
o 30–50 → Adult
o 50 → Senior
5. Find average purchase per age group.

In [37]:
customer_data = {
'CustomerID':[101,102,103,104,105,106,107],
'Age':[25,45,35,50,23,40,60],
'PurchaseAmount':[250,600,400,800,150,700,900],
'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai','Delhi','Chennai']
}


In [38]:
customer_df = pd.DataFrame(customer_data)
customer_df

,CustomerID,Age,PurchaseAmount,City
0,101,25,250,Delhi
1,102,45,600,Mumbai
2,103,35,400,Delhi
3,104,50,800,Chennai
4,105,23,150,Mumbai
5,106,40,700,Delhi
6,107,60,900,Chennai


In [39]:
# Average purchase amount by city

avg_by_city = customer_df.groupby('City')['PurchaseAmount'].mean()
print(avg_by_city)

City
Chennai    850.0
Delhi      450.0
Mumbai     375.0
Name: PurchaseAmount, dtype: float64


In [40]:
# Customers with purchase above overall average

overall_avg = customer_df['PurchaseAmount'].mean()

high_value_customers = customer_df[customer_df['PurchaseAmount'] > overall_avg]
print(high_value_customers)


   CustomerID  Age  PurchaseAmount     City
1         102   45             600   Mumbai
3         104   50             800  Chennai
5         106   40             700    Delhi
6         107   60             900  Chennai


In [41]:
# City generating highest revenue

total_by_city = customer_df.groupby('City')['PurchaseAmount'].sum()
top_city = total_by_city.idxmax()

print(total_by_city)
print("Top city:", top_city)

City
Chennai    1700
Delhi      1350
Mumbai      750
Name: PurchaseAmount, dtype: int64
Top city: Chennai


In [42]:
# Age Group Column

def age_group(age):
    if age < 30:
        return "Young"
    elif age <= 50:
        return "Adult"
    else:
        return "Senior"

customer_df['Age_Group'] = customer_df['Age'].apply(age_group)
customer_df

,CustomerID,Age,PurchaseAmount,City,Age_Group
0,101,25,250,Delhi,Young
1,102,45,600,Mumbai,Adult
2,103,35,400,Delhi,Adult
3,104,50,800,Chennai,Adult
4,105,23,150,Mumbai,Young
5,106,40,700,Delhi,Adult
6,107,60,900,Chennai,Senior


In [43]:
# Average purchase per age group

avg_by_age_group = customer_df.groupby('Age_Group')['PurchaseAmount'].mean()
print(avg_by_age_group)

Age_Group
Adult     625.0
Senior    900.0
Young     200.0
Name: PurchaseAmount, dtype: float64


# Time Series Sales Analysis

Generate data:
dates = pd.date_range('2024-01-01', periods=12, freq='M')
sales = [200,220,250,270,300,320,350,360,380,400,420,450]
df = pd.DataFrame({'Date':dates,'Sales':sales})
Tasks:
1. Convert Date to datetime index.
2. Compute monthly percentage growth.
3. Calculate 3-month rolling average sales.
4. Identify the month with highest growth rate.

In [44]:
dates = pd.date_range('2024-01-01', periods=12, freq='M')
sales = [200,220,250,270,300,320,350,360,380,400,420,450]
df = pd.DataFrame({'Date':dates,'Sales':sales})

/tmp/ipykernel_34148/4035140013.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range('2024-01-01', periods=12, freq='M')


In [45]:
df

,Date,Sales
0,2024-01-31,200
1,2024-02-29,220
2,2024-03-31,250
3,2024-04-30,270
4,2024-05-31,300
5,2024-06-30,320
6,2024-07-31,350
7,2024-08-31,360
8,2024-09-30,380
9,2024-10-31,400


In [46]:
# Convert Date to datetime index

df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)

print(df)

            Sales
Date             
2024-01-31    200
2024-02-29    220
2024-03-31    250
2024-04-30    270
2024-05-31    300
2024-06-30    320
2024-07-31    350
2024-08-31    360
2024-09-30    380
2024-10-31    400
2024-11-30    420
2024-12-31    450


In [47]:
# Monthly percentage growth

df['Monthly_Growth_%'] = df['Sales'].pct_change() * 100
print(df)

            Sales  Monthly_Growth_%
Date                               
2024-01-31    200               NaN
2024-02-29    220         10.000000
2024-03-31    250         13.636364
2024-04-30    270          8.000000
2024-05-31    300         11.111111
2024-06-30    320          6.666667
2024-07-31    350          9.375000
2024-08-31    360          2.857143
2024-09-30    380          5.555556
2024-10-31    400          5.263158
2024-11-30    420          5.000000
2024-12-31    450          7.142857


In [48]:
# 3-month rolling average

df['Rolling_3M_Avg'] = df['Sales'].rolling(window=3).mean()
print(df)

            Sales  Monthly_Growth_%  Rolling_3M_Avg
Date                                               
2024-01-31    200               NaN             NaN
2024-02-29    220         10.000000             NaN
2024-03-31    250         13.636364      223.333333
2024-04-30    270          8.000000      246.666667
2024-05-31    300         11.111111      273.333333
2024-06-30    320          6.666667      296.666667
2024-07-31    350          9.375000      323.333333
2024-08-31    360          2.857143      343.333333
2024-09-30    380          5.555556      363.333333
2024-10-31    400          5.263158      380.000000
2024-11-30    420          5.000000      400.000000
2024-12-31    450          7.142857      423.333333


In [49]:
# Month with highest growth rate

max_growth_month = df['Monthly_Growth_%'].idxmax()
max_growth_value = df['Monthly_Growth_%'].max()

print(max_growth_month, max_growth_value)

2024-03-31 00:00:00 13.636363636363647
